#  tensorflow 张量基础
## constant 常量张量
## ragged.constant 缺省张量，非矩阵
## sparsetensor 稀疏张量
## variable 变量

In [2]:
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np
import sklearn
import pandas as pd
import os
import sys
import time
import tensorflow as tf

from tensorflow import keras

In [4]:
t = tf.constant([[1.,2.,3.], [4.,5.,6.]])

print(t)
print('-'*20)
print(t[:,1:])
print('-'*20)
print(t[...,1])
print('-'*20)
type(t.numpy())
q =t.numpy()
q

tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
--------------------
tf.Tensor(
[[2. 3.]
 [5. 6.]], shape=(2, 2), dtype=float32)
--------------------
tf.Tensor([2. 5.], shape=(2,), dtype=float32)
--------------------


array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [6]:
t1 = tf.constant(q)
t1

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [7]:
print(t+10)
print('-'*20)
print(tf.square(t))
print('-'*20)
print(t)
print('-'*20)
print(tf.transpose(t))  # 转置
print('-'*20)
print(t @ tf.transpose(t))  # 矩阵乘法

tf.Tensor(
[[11. 12. 13.]
 [14. 15. 16.]], shape=(2, 3), dtype=float32)
--------------------
tf.Tensor(
[[ 1.  4.  9.]
 [16. 25. 36.]], shape=(2, 3), dtype=float32)
--------------------
tf.Tensor(
[[1. 2. 3.]
 [4. 5. 6.]], shape=(2, 3), dtype=float32)
--------------------
tf.Tensor(
[[1. 4.]
 [2. 5.]
 [3. 6.]], shape=(3, 2), dtype=float32)
--------------------
tf.Tensor(
[[14. 32.]
 [32. 77.]], shape=(2, 2), dtype=float32)


In [8]:
print(tf.math.log(t))
print('-'*20)
print(tf.sqrt(t))

tf.Tensor(
[[0.        0.6931472 1.0986123]
 [1.3862944 1.609438  1.7917595]], shape=(2, 3), dtype=float32)
--------------------
tf.Tensor(
[[1.        1.4142135 1.7320508]
 [2.        2.2360678 2.4494896]], shape=(2, 3), dtype=float32)


In [9]:
# ragged tensor  不规则张量非矩阵
r = tf.ragged.constant([[11, 12], [21, 22, 23], [], [41]])
# 只能取行

In [13]:
r2 = tf.ragged.constant([[51, 52],[], [], [71]])

print(tf.concat([r,r2],axis=1))

<tf.RaggedTensor [[11, 12, 51, 52], [21, 22, 23], [], [41, 71]]>


In [14]:
print(r2.to_tensor())
# 深度学习必须为tensor 矩阵

tf.Tensor(
[[51 52]
 [ 0  0]
 [ 0  0]
 [71  0]], shape=(4, 2), dtype=int32)


In [17]:
# sparse tensor 可以往前面补零,sparse tensor从第一行依次往下填位置
#sparese tensor存储节省内存空间，磁盘空间
s = tf.SparseTensor(indices = [[0, 1], [1, 0], [2, 3],[3,2]], #位置
                    values = [1., 2., 3.,5],  #值
                    dense_shape = [4, 4])  #维数
print(s)
tt = tf.sparse.to_dense(s)
tt

SparseTensor(indices=tf.Tensor(
[[0 1]
 [1 0]
 [2 3]
 [3 2]], shape=(4, 2), dtype=int64), values=tf.Tensor([1. 2. 3. 5.], shape=(4,), dtype=float32), dense_shape=tf.Tensor([4 4], shape=(2,), dtype=int64))


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0., 1., 0., 0.],
       [2., 0., 0., 0.],
       [0., 0., 0., 3.],
       [0., 0., 5., 0.]], dtype=float32)>

In [20]:
s2 = s * 2
print(tf.sparse.to_dense(s2))
s4 = tf.constant([[10., 20.],
                  [30., 40.],
                  [50., 60.],
                  [70., 80.]])
# sparse tensor 与 tensor 相乘
print(tf.sparse.sparse_dense_matmul(s, s4))

tf.Tensor(
[[ 0.  2.  0.  0.]
 [ 4.  0.  0.  0.]
 [ 0.  0.  0.  6.]
 [ 0.  0. 10.  0.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[ 30.  40.]
 [ 20.  40.]
 [210. 240.]
 [250. 300.]], shape=(4, 2), dtype=float32)


In [26]:
# sparse tensor
# sparse tensort 转为tensor  如果indices中位置无序必须要reorder
s5 = tf.SparseTensor(indices = [[0, 2], [2, 3], [0, 1]],
                    values = [1., 2., 3.],
                    dense_shape = [3, 4])
s8 = tf.sparse.reorder(s5)
print(tf.sparse.to_dense(s8))

tf.Tensor(
[[0. 3. 1. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 2.]], shape=(3, 4), dtype=float32)


In [32]:
# Variables  assign在原来空间进行修改 效率高
v = tf.Variable([[1., 2., 3.], [4., 5.,6.]])
# 变量修改需要用assign
v[0,1].assign(29)
v

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[ 1., 29.,  3.],
       [ 4.,  5.,  6.]], dtype=float32)>